# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# User.create(username: 'Primike', password_digest: '123123', first_name: 'Prince', last_name: 'Avecillas', email: "avecillasprince@yahoo.com", image_url: "https://media.istockphoto.com/photos/background-of-galaxy-and-stars-picture-id1035676256?b=1&k=20&m=1035676256&s=170667a&w=0&h=NOtiiFfDhhUhZgQ4wZmHPXxHvt3RFVD-lTmnWCeyIG4=")
# UserCourse.delete_all
# Course.delete_all
Course.create(subject: 'Quantum Mechanics', subject_image: "https://scx2.b-cdn.net/gfx/news/hires/2015/5666a45b218f7.jpg", completed: false)
Course.create(subject: 'Classical Mechanics', subject_image: "https://cdn1.byjus.com/wp-content/uploads/2018/11/physics/wp-content/uploads/2016/08/3.png", completed: false)
Course.create(subject: 'Electricity and Magnetism', subject_image: "https://cdn.vox-cdn.com/thumbor/1ZPuV80n_PVUARYlkcCorFG_Frk=/0x0:3000x3000/1200x800/filters:focal(1260x1260:1740x1740)/cdn.vox-cdn.com/uploads/chorus_image/image/50911339/electricity.0.jpg", completed: false)
Chapter.create(title: "Electrons", content: "Electrons are particles that can usually be found around the nucleous of atoms. Electrons have a very small amount of mass but have no size. Electrons are actually not like the balls in the picture but are points with no volume. All electrons are identical and it is impossible to distinguish one from another. Since electrons and other particles are very small their quantum properties are visible in experiments. Larger objects like animals have basically invisible quantum properties.", image: "https://circuitglobe.com/wp-content/uploads/2020/05/structure-of-atom1.jpg", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Wave Particle Duality", content: "In the double slit experiment light particles were shot from a laser through two openings called slits. Since they were particles they were expected to hit the board and create 2 rectangles like what would happen if you shot paintballs. Instead they created a wave like pattern in the board. This experiment led to the conclusion that light was both a wave and a particle. A wave would mean a kind of cloud of probabilities. All particles share this feature with light.", image: "https://quantumpreception.files.wordpress.com/2019/01/doubleslottest-1400x793-71-2.jpg", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Schrodinger Equation", content: "This is the famed Schrodinger equation. This equation is solved for the trident like figure called Psi. Psi describes a particle and its quantum properties like position, energy and momentum. Psi is called the wavefunction since a particle is actually a wave. Psi evaluated at different positions is called the eigenstates of a particle. Depending on certain factors a particle(Psi) can have many eigenstates each describing a unique energy amount of the particle. Using an analogy you represent a particle the eigenfunction represents all the USA and the eigenstates represent the 50 states. Depending on which state you are in you will be in a different position and will feel different weather(energy)", image: "https://2.bp.blogspot.com/--q2Mb0j2tR0/Tdr5vUK0UrI/AAAAAAAAABU/wx5WClTbj74/s1600/1242266_f496.jpg", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Wave Function", content: "This is a graph of the wavefunction Psi of a particle. Since a particle is a wave it does not have a position but a probability of positions. If the graph represented a football field the particle would most likely be found in the center since that is when the probability is the highest. Only when a particle is measured does the probability cloud disappear and a particle becomes a point and not a wave.", image: "https://lh3.googleusercontent.com/proxy/SQO8CK__jLWtz3-_FGOjDA8QCTadQ0WfnN7w-kBg_qEp9bSSW2fsbzoo4UL7Ewmys5RzAwCoRN_y0imWQZXGJw7m9GYuNVz9sjdFbq8", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Eigenfunctions", content: "This graph represents some particles eigenstates. These eigenstates are represented by Psi evaluated at different energy values shown by the numbers next to Psi. The waves show the probability cloud of a particle.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk0e9aKNNghq9LM8HtI70C0kBHikDsBAjBS7WC1cd-8hmxIg1Xbz20BVEznBniCfkJL80&usqp=CAU", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Superposition", content: "This is schrodingers cat. If the cat was a particle then the concept of alive and dead represent different positions(eigenstates) of a particle. Until you look inside the box the cat is in it is basically both alive and dead to you. The same way until you look at an electron it is actually in multiple positions(eigenstates) represented by a probability cloud.", image: "https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL3F1YW50dW0taW1tb3J0YWxpdHktaWxsdXN0cmF0aW9uLmdpZiIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6MjkwfX19", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Heisenberg Uncertainty Principle", content: "This is Heisenberg's uncertainty principle it states that you can never know both the position and momentum of a particle. If you look at a ball rolling on the ground you can tell the balls position and momentum(velocity) at a certain time. The same is not true of particles and tiny objects. You either measure the position or the speed you cant know both.", image: "https://cdn.zmescience.com/wp-content/uploads/2020/05/1_nEaJVpcLRDNLUKXttypcFA.png", course_id: Course.find_by(subject: "Quantum Mechanics").id)
Chapter.create(title: "Tunneling", content: "This is the Quantum Phenomenon of tunneling. In classical physics(Our world) a ball can only roll over a barrier or it is reflected if it hits a hard wall. In the quantum world a particle and actually teleport across a barrier or wall if it has a high enough energy. The higher the energy the higher the probability that an electron launched against a barrier will be able to teleport across.", image: "https://cosmosmagazine.com/wp-content/uploads/2020/04/190318-quantum-pr.jpg", course_id: Course.find_by(subject: "Quantum Mechanics").id)
